// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvp9zaNFIoWK5G6DhS7XJcgsFxAoF-F4',
    appId: '1:921830428079:web:308d1b30981ac4fa95f35a',
    messagingSenderId: '921830428079',
    projectId: 'testandoflutterfirebase',
    authDomain: 'testandoflutterfirebase.firebaseapp.com',
    databaseURL: 'https://testandoflutterfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'testandoflutterfirebase.appspot.com',
    measurementId: 'G-XSVS1QX11Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNcOB9dcBmqREmK7W0Ogp9fS_NFELE3z0',
    appId: '1:921830428079:android:c5fc6cb6837391cc95f35a',
    messagingSenderId: '921830428079',
    projectId: 'testandoflutterfirebase',
    databaseURL: 'https://testandoflutterfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'testandoflutterfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUB0aASa8c2rAz3mhdK_NTb65RT9GBqs',
    appId: '1:921830428079:ios:92729de084752fa295f35a',
    messagingSenderId: '921830428079',
    projectId: 'testandoflutterfirebase',
    databaseURL: 'https://testandoflutterfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'testandoflutterfirebase.appspot.com',
    iosClientId: '921830428079-m06dmk9pnb0jnd17m87v844vr8u1lf2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.aprendendoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUB0aASa8c2rAz3mhdK_NTb65RT9GBqs',
    appId: '1:921830428079:ios:92729de084752fa295f35a',
    messagingSenderId: '921830428079',
    projectId: 'testandoflutterfirebase',
    databaseURL: 'https://testandoflutterfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'testandoflutterfirebase.appspot.com',
    iosClientId: '921830428079-m06dmk9pnb0jnd17m87v844vr8u1lf2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.aprendendoFirebase',
  );
}
